# Generated by Django 3.0.1 on 2020-01-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20200104_0038'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='Empleado',
        ),
    ]
